### PR TITLE
Value-only items and preferred terms field transformations

### PR DESCRIPTION
**Pull request by awead**
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**
* * *

**JIRA Ticket**: 
[(SS-353)](https://at-harvard.atlassian.net/browse/SS-353)
[SS-354](https://at-harvard.atlassian.net/browse/SS-354)

# What does this Pull Request do?
Creates transforms for:

- Date Description
- Earliest Date
- Latest Date
- State/Edition
- Measurements
- Culture
- Work Type
- Style/Period
- Materials
- Techniques
- Subject (AAT)

## Resulting XML

``` xml
<viaRecord>
   <work>
      <freeDate>1900-1901 (creation); 2000-2001</freeDate>
      <dimensions>base: area 100 square feet; base: perimeter 40 feet; frame: height 50 feet; frame: length 50 feet; frame: width 25 feet</dimensions>
      <state>name 1. description 1; name 2. description 2</state>
      <endDate>2001</endDate>
      <structuredDate>
         <beginDate>1900</beginDate>
         <endDate>2001</endDate>
      </structuredDate>
      <workType>blueprints (reprographic copies)</workType>
      <workType>amphitheaters (built works)</workType>
      <materials>concrete</materials>
      <materials>steel (alloy)</materials>
      <culture>
         <term>American</term>
      </culture>
      <culture>
         <term>Mexican</term>
      </culture>
      <topic>
         <term>societies' buildings</term>
      </topic>
      <topic>
         <term>building sites</term>
      </topic>
      <topic>
         <term>metal</term>
      </topic>
      <materials>construction (assembling)</materials>
      <materials>construction drawings</materials>
      <style>
         <term>Modern (styles and periods)</term>
      </style>
      <style>
         <term>Art Deco</term>
      </style>
      <style>
         <term>Bauhaus</term>
      </style>
   </work>
</viaRecord>

```

# How should this be tested?

Unit tests are included.

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? yes
- integration tests? no

# Interested parties
Tag (@ mention) interested parties

[SS-354]: https://at-harvard.atlassian.net/browse/SS-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by awead** [comment]
I've named all the new files under a `v2` directory, but I'm fine with calling this something else more meaningful.

**Comment by awead** [comment]
@michael-lts Ok, I found a different way that I think will be better moving forward. I'm sharing test fixtures in the `conftest.py` file and spilt up the other tests into two different files based on the kinds of fields that they're testing. Let me know what you think!

**Comment by michael-lts** [comment]
@awead , yes looks good, and the tests are working properly, thanks!

**Review by michael-lts — APPROVED** [review]
Visual inspection looks good
Running pytest at top level now working after requested modification

**Pull request merged**
